//! Golden conformance tests against the vectors generated by the Python
//! reference (`gen_vectors.py`, `steward_vectors.py`). The crate conforms iff:
//!   - decode(canonical hex) re-encodes byte-identically (deterministic CBOR
//!     agreement), and rejects nothing it shouldn't
//!   - core hashes and attestation IDs match
//!   - every published signature verifies; every negative vector fails

use std::collections::HashMap;

use comms_core::bundle::{
    author_general_claim, build_seal, make_bundle, media_key, parse_bundle, verify_seal, Bundle,
    ClaimSpec,
};
use comms_core::steward::{
    community_id, community_sign, verify_chain, verify_community_attestation, Attestation,
    Descriptor, SignatureObject, StewardError,
};
use comms_core::{attestation_id, cbor, core_hash, personal_verify, Value};
use ed25519_dalek::SigningKey;

const ATTEST_VECTORS: &str = include_str!("data/attest-1.0-test-vectors.json");
const BUNDLE_VECTORS: &str = include_str!("data/attest-1.0-bundle-vectors.json");
const STEWARD_VECTORS: &str = include_str!("data/steward-test-vectors.json");

fn hex32(s: &str) -> [u8; 32] {
    <[u8; 32]>::try_from(hex::decode(s).unwrap().as_slice()).unwrap()
}

fn hex64(s: &str) -> [u8; 64] {
    <[u8; 64]>::try_from(hex::decode(s).unwrap().as_slice()).unwrap()
}

/// Decode a vector's canonical core hex, prove round-trip byte identity,
/// prove hash + ID, return the core.
fn conformant_core(v: &serde_json::Value) -> Value {
    let bytes = hex::decode(v["canonical_core_cbor_hex"].as_str().unwrap()).unwrap();
    let core = cbor::decode(&bytes).expect("vector core must decode");
    assert_eq!(
        cbor::encode(&core),
        bytes,
        "re-encoding must be byte-identical (deterministic CBOR agreement)"
    );
    assert_eq!(core_hash(&core), hex32(v["core_hash_hex"].as_str().unwrap()));
    assert_eq!(attestation_id(&core), v["attestation_id"].as_str().unwrap());
    core
}

#[test]
fn attest_vectors_conform() {
    let j: serde_json::Value = serde_json::from_str(ATTEST_VECTORS).unwrap();
    let keys = &j["keys"];
    let pubkey_of = |steward_id: &str| -> [u8; 32] {
        keys.as_array()
            .unwrap()
            .iter()
            .find(|k| k["steward_id"] == steward_id)
            .map(|k| hex32(k["public_key_hex"].as_str().unwrap()))
            .expect("unknown steward id in vector")
    };

    // Vector 1: general-claim, author signature
    let v1 = &j["vectors"][0];
    let core1 = conformant_core(v1);
    let s = &v1["signatures"][0];
    let by = s["by"].as_str().unwrap();
    assert!(personal_verify(
        &core1,
        by,
        s["role"].as_str().unwrap(),
        s["signed_at"].as_str().unwrap(),
        &pubkey_of(by),
        &hex64(s["signature_hex"].as_str().unwrap()),
    ));

    // Negative: role swap MUST fail (the A1.3 fix)
    assert!(!personal_verify(
        &core1,
        by,
        "sponsor",
        s["signed_at"].as_str().unwrap(),
        &pubkey_of(by),
        &hex64(s["signature_hex"].as_str().unwrap()),
    ));

    // Vector 2: added witness signature, same attestation id
    let v2 = &j["vectors"][1];
    assert_eq!(v2["attestation_id"], v1["attestation_id"]);
    let w = &v2["signatures_added"][0];
    let wby = w["by"].as_str().unwrap();
    assert!(personal_verify(
        &core1,
        wby,
        w["role"].as_str().unwrap(),
        w["signed_at"].as_str().unwrap(),
        &pubkey_of(wby),
        &hex64(w["signature_hex"].as_str().unwrap()),
    ));

    // Vector 3: endorsement referencing vector 1
    let v3 = &j["vectors"][2];
    let core3 = conformant_core(v3);
    let s3 = &v3["signatures"][0];
    let by3 = s3["by"].as_str().unwrap();
    assert!(personal_verify(
        &core3,
        by3,
        s3["role"].as_str().unwrap(),
        s3["signed_at"].as_str().unwrap(),
        &pubkey_of(by3),
        &hex64(s3["signature_hex"].as_str().unwrap()),
    ));
}

fn parse_sig(s: &serde_json::Value) -> SignatureObject {
    SignatureObject {
        by: s["by"].as_str().unwrap().to_owned(),
        alg: s["alg"].as_str().unwrap().to_owned(),
        role: s["role"].as_str().unwrap().to_owned(),
        signed_at: s["signed_at"].as_str().unwrap().to_owned(),
        keyset: s.get("keyset").and_then(|k| k.as_str()).map(str::to_owned),
        signature: hex::decode(s["signature"].as_str().unwrap()).unwrap(),
    }
}

fn parse_attestation(v: &serde_json::Value) -> Attestation {
    Attestation {
        core: conformant_core(v),
        signatures: v["signatures"]
            .as_array()
            .unwrap()
            .iter()
            .map(parse_sig)
            .collect(),
    }
}

struct StewardFixture {
    j: serde_json::Value,
    cid: String,
    cid2: String,
    atts: Vec<Attestation>,
    store: HashMap<String, Attestation>,
    seeds: HashMap<String, [u8; 32]>,
}

fn steward_fixture() -> StewardFixture {
    let j: serde_json::Value = serde_json::from_str(STEWARD_VECTORS).unwrap();
    let cid = j["community_id"].as_str().unwrap().to_owned();
    let cid2 = j["successor_community_id"].as_str().unwrap().to_owned();
    let atts: Vec<Attestation> = j["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .map(parse_attestation)
        .collect();
    // vectors: [0]=K0 genesis, [1]=rule, [2]=K1 rotation, [3]=rule2, [4]=KS, [5]=succession
    let mut store = HashMap::new();
    for i in [0usize, 2, 4] {
        store.insert(atts[i].id(), atts[i].clone());
    }
    let seeds = j["keys"]
        .as_array()
        .unwrap()
        .iter()
        .map(|k| {
            (
                k["name"].as_str().unwrap().to_owned(),
                hex32(k["ed25519_seed_hex"].as_str().unwrap()),
            )
        })
        .collect();
    StewardFixture { j, cid, cid2, atts, store, seeds }
}

#[test]
fn steward_chain_and_community_signatures_conform() {
    let f = steward_fixture();

    // Genesis descriptor hashes to the published community id
    let desc0 = Descriptor::from_value(
        f.atts[0].core.get("c").unwrap().get("descriptor").unwrap(),
    )
    .unwrap();
    assert_eq!(community_id(&desc0), f.cid);

    // Chain K0 -> K1 verifies and yields K1's descriptor
    let k1_id = f.atts[2].id();
    let desc1 = verify_chain(&f.cid, &k1_id, &f.store).unwrap();
    assert_eq!(
        desc1,
        Descriptor::from_value(f.atts[2].core.get("c").unwrap().get("descriptor").unwrap())
            .unwrap()
    );

    // rule under K0 and rule2 under K1 (through the chain) both verify
    verify_community_attestation(&f.atts[1], &f.cid, &f.store).unwrap();
    verify_community_attestation(&f.atts[3], &f.cid, &f.store).unwrap();

    // Succession: successor community signature verifies under its own chain,
    // and both personal witness signatures verify on the same attestation —
    // math and testimony side by side in one `s` array.
    verify_community_attestation(&f.atts[5], &f.cid2, &f.store).unwrap();
    let keys = f.j["keys"].as_array().unwrap();
    let witness_sigs: Vec<&SignatureObject> = f.atts[5]
        .signatures
        .iter()
        .filter(|s| s.alg == "ed25519")
        .collect();
    assert_eq!(witness_sigs.len(), 2);
    for s in witness_sigs {
        let pk = keys
            .iter()
            .find(|k| k["personal_steward_id"] == s.by.as_str())
            .map(|k| hex32(k["public_key_hex"].as_str().unwrap()))
            .unwrap();
        assert!(personal_verify(
            &f.atts[5].core,
            &s.by,
            &s.role,
            &s.signed_at,
            &pk,
            &<[u8; 64]>::try_from(s.signature.as_slice()).unwrap(),
        ));
    }
}

#[test]
fn negative_sub_threshold_fails() {
    let f = steward_fixture();
    let mut att = f.atts[3].clone(); // rule2 under K1, threshold 2
    let sig = &mut att.signatures[0];
    // Truncate the inner array to a single signature
    let Value::Array(inner) = cbor::decode(&sig.signature).unwrap() else {
        panic!()
    };
    sig.signature = cbor::encode(&Value::Array(inner[..1].to_vec()));
    assert!(matches!(
        verify_community_attestation(&att, &f.cid, &f.store),
        Err(StewardError::SetSignatureInvalid)
    ));
}

#[test]
fn negative_role_swap_on_set_signature_fails() {
    let f = steward_fixture();
    let mut att = f.atts[3].clone();
    att.signatures[0].role = "witness".to_owned(); // was "community"
    assert!(verify_community_attestation(&att, &f.cid, &f.store).is_err());
}

#[test]
fn negative_keyset_repointing_fails() {
    let f = steward_fixture();
    let mut att = f.atts[3].clone(); // signed under K1
    att.signatures[0].keyset = Some(f.atts[0].id()); // re-point at K0
    // The keyset field is inside the signed payload, so this must fail even
    // though K0 is a perfectly valid chain link.
    assert!(verify_community_attestation(&att, &f.cid, &f.store).is_err());
}

#[test]
fn negative_hostile_takeover_fails() {
    let f = steward_fixture();
    // Eve and Fen forge a keyset claiming to supersede K0, beautifully signed
    // by their own keys — but never authorized by K0's threshold.
    let eve = SigningKey::from_bytes(&f.seeds["Eve"]);
    let fen = SigningKey::from_bytes(&f.seeds["Fen"]);
    let desc_x = Descriptor::new(
        vec![*eve.verifying_key().as_bytes(), *fen.verifying_key().as_bytes()],
        2,
    )
    .unwrap();
    let k0_id = f.atts[0].id();
    let kx_core = Value::Map(vec![
        (Value::text("v"), Value::U64(1)),
        (Value::text("t"), Value::text("comms.attestation/1")),
        (
            Value::text("c"),
            Value::Map(vec![
                (Value::text("t"), Value::text("keyset/1")),
                (Value::text("community"), Value::text(&f.cid)),
                (Value::text("descriptor"), desc_x.to_value()),
            ]),
        ),
        (
            Value::text("f"),
            Value::Map(vec![
                (Value::text("issued_at"), Value::text("2026-07-02T00:00:00Z")),
                (Value::text("language"), Value::text("en")),
            ]),
        ),
        (
            Value::text("r"),
            Value::Array(vec![Value::Map(vec![
                (Value::text("role"), Value::text("supersedes")),
                (Value::text("id"), Value::text(&k0_id)),
            ])]),
        ),
    ]);
    let kx_id = attestation_id(&kx_core);
    // Variant A: signature claims validity under the forged keyset itself
    let sig_self = community_sign(
        &kx_core, &f.cid, "community", "2026-07-02T00:00:01Z", &kx_id, &[eve.clone(), fen.clone()],
    );
    let mut store = f.store.clone();
    store.insert(
        kx_id.clone(),
        Attestation { core: kx_core.clone(), signatures: vec![sig_self] },
    );
    assert!(matches!(
        verify_chain(&f.cid, &kx_id, &store),
        Err(StewardError::RotationNotPredecessorAuthorized)
    ));

    // Variant B: signature correctly references K0 but Eve/Fen aren't in it —
    // their inner signatures are ignored as padding, threshold unmet.
    let sig_k0 = community_sign(
        &kx_core, &f.cid, "community", "2026-07-02T00:00:01Z", &k0_id, &[eve, fen],
    );
    store.insert(
        kx_id.clone(),
        Attestation { core: kx_core, signatures: vec![sig_k0] },
    );
    assert!(matches!(
        verify_chain(&f.cid, &kx_id, &store),
        Err(StewardError::SetSignatureInvalid)
    ));
}

#[test]
fn rust_can_extend_the_chain_python_started() {
    // Cross-implementation interop in one test: Rust rotates K1 -> K2 using
    // seeds published in the Python-generated vectors, then verifies the
    // whole chain including its own new link.
    let f = steward_fixture();
    let ada = SigningKey::from_bytes(&f.seeds["Ada"]);
    let bea = SigningKey::from_bytes(&f.seeds["Bea"]);
    let dov = SigningKey::from_bytes(&f.seeds["Dov"]);
    let eve = SigningKey::from_bytes(&f.seeds["Eve"]);

    let desc2 = Descriptor::new(
        vec![
            *bea.verifying_key().as_bytes(),
            *dov.verifying_key().as_bytes(),
            *eve.verifying_key().as_bytes(),
        ],
        2,
    )
    .unwrap();
    let k1_id = f.atts[2].id();
    let k2_core = Value::Map(vec![
        (Value::text("v"), Value::U64(1)),
        (Value::text("t"), Value::text("comms.attestation/1")),
        (
            Value::text("c"),
            Value::Map(vec![
                (Value::text("t"), Value::text("keyset/1")),
                (Value::text("community"), Value::text(&f.cid)),
                (Value::text("descriptor"), desc2.to_value()),
            ]),
        ),
        (
            Value::text("f"),
            Value::Map(vec![
                (Value::text("issued_at"), Value::text("2026-08-01T00:00:00Z")),
                (Value::text("language"), Value::text("en")),
            ]),
        ),
        (
            Value::text("r"),
            Value::Array(vec![Value::Map(vec![
                (Value::text("role"), Value::text("supersedes")),
                (Value::text("id"), Value::text(&k1_id)),
            ])]),
        ),
    ]);
    let k2_id = attestation_id(&k2_core);
    // Authorized by K1's keyset: Ada + Dov sign (both in K1)
    let sig = community_sign(
        &k2_core, &f.cid, "community", "2026-08-01T00:00:01Z", &k1_id, &[ada, dov],
    );
    let mut store = f.store.clone();
    store.insert(k2_id.clone(), Attestation { core: k2_core, signatures: vec![sig] });
    let got = verify_chain(&f.cid, &k2_id, &store).unwrap();
    assert_eq!(got, desc2);
}

#[test]
fn bundle_vectors_conform() {
    let j: serde_json::Value = serde_json::from_str(BUNDLE_VECTORS).unwrap();

    // Positive case: parse the full bundle and verify its seal
    let bundle_hex = j["bundle"]["canonical_cbor_hex"].as_str().unwrap();
    let bundle_bytes = hex::decode(bundle_hex).unwrap();
    let bundle = parse_bundle(&bundle_bytes).expect("positive bundle must parse");

    let report = verify_seal(&bundle);
    assert!(report.ok, "seal must verify on the positive bundle");
    assert_eq!(
        report.sealed_by.as_deref(),
        Some(j["seal"]["signature"]["by"].as_str().unwrap()),
        "sealed_by must match the signing steward"
    );
    assert!(report.missing.is_empty(), "no members should be missing");
    assert!(report.extra.is_empty(), "no extra members should be present");

    // The bundle has exactly 3 attestations (2 members + 1 seal)
    assert_eq!(bundle.attestations.len(), 3);

    // Media key example
    let body_utf8 = j["media_key_example"]["body_utf8"].as_str().unwrap();
    let expected_key = j["media_key_example"]["media_key"].as_str().unwrap();
    assert_eq!(media_key(body_utf8.as_bytes()), expected_key);
}

/// The signer seed + pinned timestamps the bundle vector recorded for its seal.
struct SealFixture {
    members: Vec<Attestation>,
    published_seal: Attestation,
    sk: SigningKey,
    seal_id: String,
    description: String,
    created_at: String,
    issued_at: String,
    signed_at: String,
    bundle_bytes: Vec<u8>,
}

fn seal_fixture() -> SealFixture {
    let j: serde_json::Value = serde_json::from_str(BUNDLE_VECTORS).unwrap();
    let bundle_bytes = hex::decode(j["bundle"]["canonical_cbor_hex"].as_str().unwrap()).unwrap();
    let parsed = parse_bundle(&bundle_bytes).expect("positive bundle must parse");
    let seal_id = j["bundle"]["seal_id"].as_str().unwrap().to_owned();

    // Members are every non-seal attestation, in their original (array) order.
    let members: Vec<Attestation> = parsed
        .attestations
        .iter()
        .filter(|a| a.id() != seal_id)
        .cloned()
        .collect();
    let published_seal = parsed
        .attestations
        .iter()
        .find(|a| a.id() == seal_id)
        .unwrap()
        .clone();

    // The seal signer's seed, found by matching the seal's `by` steward id.
    let by = j["seal"]["signature"]["by"].as_str().unwrap();
    let seed = j["keys"]
        .as_array()
        .unwrap()
        .iter()
        .find(|k| k["steward_id"] == by)
        .map(|k| hex32(k["ed25519_seed_hex"].as_str().unwrap()))
        .expect("seal signer seed must be in the vector");

    SealFixture {
        members,
        published_seal,
        sk: SigningKey::from_bytes(&seed),
        seal_id,
        // The seal manifest's own description (NOT the bundle JSON annotation),
        // and the timestamps the vector pinned (Python stamps now() by default).
        description: j["seal"]["manifest"]["description"].as_str().unwrap().to_owned(),
        created_at: j["seal"]["manifest"]["created_at"].as_str().unwrap().to_owned(),
        issued_at: j["seal"]["core"]["f"]["issued_at"].as_str().unwrap().to_owned(),
        signed_at: j["seal"]["signature"]["signed_at"].as_str().unwrap().to_owned(),
        bundle_bytes,
    }
}

#[test]
fn rust_build_seal_matches_python_byte_for_byte() {
    // Create-side crypto contract: given the same members, signer seed, and
    // pinned timestamps, Rust `build_seal` reproduces the exact seal Python's
    // `bundle.seal` produced — same id, same deterministic signature, same bytes.
    let f = seal_fixture();
    let j: serde_json::Value = serde_json::from_str(BUNDLE_VECTORS).unwrap();

    let seal = build_seal(&f.members, &f.sk, &f.description, &f.created_at, &f.issued_at, &f.signed_at);
    assert_eq!(seal.id(), f.seal_id, "rebuilt seal id must match the vector");
    assert_eq!(
        hex::encode(&seal.signatures[0].signature),
        j["seal"]["signature"]["signature_hex"].as_str().unwrap(),
        "deterministic Ed25519 signature must match byte-for-byte",
    );
    assert_eq!(
        seal.to_cbor(),
        f.published_seal.to_cbor(),
        "rebuilt seal envelope must be byte-identical",
    );
}

#[test]
fn rust_assembles_the_vector_bundle_bytes() {
    // Container contract: assembling [members..., seal] (the vector's bundle has
    // no media and no informational manifest) re-encodes to the exact Python
    // bundle bytes — proving Rust can *create* the whole container from scratch.
    let f = seal_fixture();
    let seal = build_seal(&f.members, &f.sk, &f.description, &f.created_at, &f.issued_at, &f.signed_at);

    let mut attestations = f.members.clone();
    attestations.push(seal);
    let bundle = Bundle { attestations, media: HashMap::new(), manifest: None };

    assert_eq!(bundle.to_cbor(), f.bundle_bytes, "assembled bundle must equal Python bytes");
    assert!(verify_seal(&bundle).ok, "self-assembled bundle must verify");
}

#[test]
fn make_bundle_seals_and_attaches_manifest() {
    // `make_bundle` (the `bundle.make` port) appends a seal and an informational
    // bundle manifest, and round-trips through parse/verify.
    let f = seal_fixture();
    let bundle = make_bundle(
        f.members.clone(),
        HashMap::new(),
        Some(&f.sk),
        "courier run 7",
        &f.created_at,
        &f.issued_at,
        &f.signed_at,
    );
    assert_eq!(bundle.attestations.len(), f.members.len() + 1, "seal appended");
    assert!(bundle.manifest.is_some(), "manifest attached when sealed");

    let reparsed = parse_bundle(&bundle.to_cbor()).expect("make_bundle output must parse");
    let report = verify_seal(&reparsed);
    assert!(report.ok, "make_bundle seal must verify after a round trip");
    assert_eq!(report.sealed_by.as_deref(), Some(f.published_seal.signatures[0].by.as_str()));
}

#[test]
fn parse_then_reencode_is_byte_identical() {
    // Round-trip: the serializer is the exact inverse of the parser on a real
    // bundle (no creation involved) — guards `to_envelope_value`/`to_cbor`.
    let j: serde_json::Value = serde_json::from_str(BUNDLE_VECTORS).unwrap();
    let bundle_bytes = hex::decode(j["bundle"]["canonical_cbor_hex"].as_str().unwrap()).unwrap();
    let parsed = parse_bundle(&bundle_bytes).expect("bundle must parse");
    assert_eq!(parsed.to_cbor(), bundle_bytes, "re-encode must round-trip");
}

#[test]
fn bundle_dropped_member_fails() {
    let j: serde_json::Value = serde_json::from_str(BUNDLE_VECTORS).unwrap();
    let neg = &j["negative_vectors"][0];
    assert_eq!(neg["name"].as_str().unwrap(), "dropped member must fail the seal");

    let bytes = hex::decode(neg["canonical_cbor_hex"].as_str().unwrap()).unwrap();
    let bundle = parse_bundle(&bytes).expect("dropped-member bundle must parse");
    let report = verify_seal(&bundle);

    assert!(!report.ok, "seal must fail when a member is dropped");
    let expected_missing = neg["expect"]["missing"][0].as_str().unwrap();
    assert!(
        report.missing.contains(&expected_missing.to_owned()),
        "missing must contain the dropped member id"
    );
    assert!(report.extra.is_empty());
}

#[test]
fn bundle_smuggled_member_fails() {
    let j: serde_json::Value = serde_json::from_str(BUNDLE_VECTORS).unwrap();
    let neg = &j["negative_vectors"][1];
    assert_eq!(neg["name"].as_str().unwrap(), "smuggled member must fail the seal");

    let bytes = hex::decode(neg["canonical_cbor_hex"].as_str().unwrap()).unwrap();
    let bundle = parse_bundle(&bytes).expect("smuggled-member bundle must parse");
    let report = verify_seal(&bundle);

    assert!(!report.ok, "seal must fail when a member is smuggled");
    let expected_extra = neg["expect"]["extra"][0].as_str().unwrap();
    assert!(
        report.extra.contains(&expected_extra.to_owned()),
        "extra must contain the smuggled member id"
    );
    assert!(report.missing.is_empty());
}

/// The create-side path (`author_general_claim`, the engine behind
/// `comms-verify attest`) must reproduce the published general-claim vector
/// byte-for-byte: same canonical core, same id, same deterministic author
/// signature. This pins authoring to the Python reference the same way the
/// seal golden pins `build_seal`.
#[test]
fn author_general_claim_reproduces_the_reference_vector() {
    let j: serde_json::Value = serde_json::from_str(ATTEST_VECTORS).unwrap();
    let v = &j["vectors"][0];

    // Source the authoring inputs from the authoritative canonical core bytes
    // (the display `core` JSON does not carry the raw body), then prove we can
    // reconstruct those exact bytes from the semantic inputs.
    let original = hex::decode(v["canonical_core_cbor_hex"].as_str().unwrap()).unwrap();
    let core = cbor::decode(&original).unwrap();
    let claim = core.get("c").unwrap();
    let content = claim.get("content").unwrap();
    let frame = core.get("f").unwrap();

    let body = content.get("body").and_then(Value::as_bytes).unwrap().to_vec();
    let spec = ClaimSpec {
        about: claim.get("about").and_then(Value::as_text).unwrap(),
        kind: claim.get("kind").and_then(Value::as_text).unwrap(),
        body: &body,
        media_type: content.get("media_type").and_then(Value::as_text).unwrap(),
        support: &[],
        language: frame.get("language").and_then(Value::as_text).unwrap(),
        community: None,
        occasion: None,
        issued_at: frame.get("issued_at").and_then(Value::as_text).unwrap(),
    };

    let sig = &v["signatures"][0];
    // The author key is seed 01*32 per the vectors' key table.
    let sk = SigningKey::from_bytes(&hex32(&"01".repeat(32)));
    let att = author_general_claim(&spec, &sk, sig["role"].as_str().unwrap(), sig["signed_at"].as_str().unwrap());

    assert_eq!(
        hex::encode(cbor::encode(&att.core)),
        v["canonical_core_cbor_hex"].as_str().unwrap(),
        "authored core must match the reference bytes"
    );
    assert_eq!(att.id(), v["attestation_id"].as_str().unwrap());
    assert_eq!(
        hex::encode(&att.signatures[0].signature),
        sig["signature_hex"].as_str().unwrap(),
        "deterministic author signature must match the reference"
    );
}
